<?php
return [
    'section_1' => "Education",
    'section_1_content' => "With education, students should have the right basis of thinking in deciding things in the campus world and off campus. And students should have the right to obtain a proper and appropriate education, such as professional lecturers, as well as soft skills education.",
    'section_2' => "Research",
    'section_2_content' => "Penelitain activities have a very important role in the framework of the advancement of science and technology. Without research, the development of science and technology will become hampered. This research does not stand alone, but it must be seen the interrelationship in development in a broad sense, namely penelitain not only for the necessary things or directly can be used by the community at that time, but must be seen with projections of the future. In other words, research in Higher Education is not only directed to applied research, but also at the same time carry out research on basic sciences whose benefits only feel important in the future.",
    'section_3' => "Devotion",
    'section_3_content' => "Community service should be interpreted in the framework of the application of science and technology that has been developed in universities, especially as a result of various researches. Community service is a series of activities in the framework of the contribution of universities to the community that has concrete characteristics and directly perceived benefits in a relatively short time. This activity can be done on the initiative of individuals or groups of members of the college academic community towards the community or to the initiatives of the relevant universities that are nonprofit (not for profit). With this activity, it is expected that there is feedback from the community to universities, which can then be used as material for further development of science and technology. Examples of implementation such as village development, training and counseling of village communities, tutoring in children, social services, KKN-PPL and so on.",
]
?>
