<?php
return [
    'section_1' => "Pendidikan",
    'section_1_content' => "Dengan pendidikan, mahasiswa hendaknya punya dasar berpikir yang benar dalam memutuskan berbagai hal di dunia kampus maupun luar kampus. Dan seharusnya mahasiswa mempunyai hak untuk memperoleh pendidikan yang layak dan sesuai, seperti dosen yang profesional, serta pendidikan softskill.",
    'section_2' => "Penelitian",
    'section_2_content' => "Kegiatan penelitain mempunyai peranan yang sangat penting dalam rangka kemajuan ilmu pengetahuan dan teknologi. Tanpa penelitian maka pengembangan ilmu pengetahuan dan teknologi akan menjadi terhambat. Penelitian ini tidaklah berdiri sendiri, akan tetapi harus dilihat keterkaitannya dalam pembangunan dalam arti luas, yakni penelitain tidak semata-mata hanya untuk hal yang diperlukan atau langsung dapat digunakan oleh masyarakat pada saat itu saja, akan tetapi harus dilihat dengan proyeksi kemasa depan. Dengan kata lain penelitian di Pergurun Tinggi tidak hanya diarahkan untuk penelitian terapan saja, tetapi juga sekaligus melaksanakan penelitian ilmu-ilmu dasar yang manfaatnya baru terasa penting dimasa yang akan datang.",
    'section_3' => "Pengabdian",
    'section_3_content' => "Dharma pengabdian pada masyarakat harus diartiakan dalam rangka penerapan ilmu pengetahuan dan teknologi yang telah dikembangkan di Perguruan Tinggi, khususnya sebagi hasil dari berbagai penelitian. Pengabdian pada masyarakat merupakan serangkaian aktivitas dalam rangka kontribusi perguruan tinggi terhadap masyarakat yang bersiafat konkrit dan langsung dirasakan manfaatnya dalam waktu yang relatif pendek. Aktivitas ini dapat dilakukan atas inisiatif individu atau kelompok anggota civitas akademika perguruan tinggi terhadap masyarakat maupun terhadap inisiatif perguruan tinggi yang bersangkutan yang bersifat nonprofit (tidak mencari keuntungan). Dengan aktivitas ini diharapkan adanya umpan balik dari masyarakat ke perguruan tinggi, yang selanjutnya dapat digunakan sebagai bahan pengembangan ilmu pengetahuan dan teknologi lebih lanjut. Contoh pelaksanaannya seperti bina desa, pelatihan dan penyuluhan masyarakat desa, bimbingan belajar pada anak-anak, bakti sosial, KKN-PPL dan lain sebagainya.",
]
?>
